// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunriseWeb.Data;

#nullable disable

namespace SunriseWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240923153117_addCountries")]
    partial class addCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SunriseWeb.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryNameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalityARFemale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalityARMale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalityEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("SunriseWeb.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlaceAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlaceEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentGradeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("IDEndDate")
                        .HasColumnType("date");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalityAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalityEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PassportEndDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSchoolAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSchoolEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentStatusFlag")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 4,
                            AdmissionDate = new DateOnly(2024, 9, 23),
                            BirthDate = new DateOnly(2024, 9, 23),
                            BirthPlaceAR = "",
                            BirthPlaceEN = "مصر",
                            CreatedBy = "",
                            CurrentClass = "BA",
                            CurrentGradeID = "4",
                            DateCreated = new DateTime(2024, 9, 23, 18, 31, 16, 281, DateTimeKind.Local).AddTicks(4743),
                            DateUpdated = new DateTime(2024, 9, 23, 18, 31, 16, 281, DateTimeKind.Local).AddTicks(4754),
                            Gender = "Male",
                            IDEndDate = new DateOnly(2024, 9, 23),
                            IDNumber = "12",
                            NationalityAR = "مصر",
                            NationalityEN = "Egypt",
                            Passport = "A12",
                            PassportEndDate = new DateOnly(2024, 9, 23),
                            PhoneNumber1 = "",
                            PhoneNumber2 = "",
                            PreviousSchoolAR = "مدارس",
                            PreviousSchoolEN = "",
                            StudentNameAR = "معاذ",
                            StudentNameEN = "Moaz",
                            StudentStatusFlag = 0,
                            UpdatedBy = ""
                        },
                        new
                        {
                            StudentID = 5,
                            AdmissionDate = new DateOnly(2024, 9, 23),
                            BirthDate = new DateOnly(2024, 9, 23),
                            BirthPlaceAR = "كندا",
                            BirthPlaceEN = "",
                            CreatedBy = "",
                            CurrentClass = "BA",
                            CurrentGradeID = "6",
                            DateCreated = new DateTime(2024, 9, 23, 18, 31, 16, 281, DateTimeKind.Local).AddTicks(4759),
                            DateUpdated = new DateTime(2024, 9, 23, 18, 31, 16, 281, DateTimeKind.Local).AddTicks(4760),
                            Gender = "",
                            IDEndDate = new DateOnly(2024, 9, 23),
                            IDNumber = "22",
                            NationalityAR = "كندا",
                            NationalityEN = "Canada",
                            Passport = "A22",
                            PassportEndDate = new DateOnly(2024, 9, 23),
                            PhoneNumber1 = "",
                            PhoneNumber2 = "",
                            PreviousSchoolAR = "شروق",
                            PreviousSchoolEN = "",
                            StudentNameAR = "موزة",
                            StudentNameEN = "Moza",
                            StudentStatusFlag = 0,
                            UpdatedBy = ""
                        },
                        new
                        {
                            StudentID = 6,
                            AdmissionDate = new DateOnly(2024, 9, 23),
                            BirthDate = new DateOnly(2024, 9, 23),
                            BirthPlaceAR = "السعودية",
                            BirthPlaceEN = "",
                            CreatedBy = "",
                            CurrentClass = "GB",
                            CurrentGradeID = "5",
                            DateCreated = new DateTime(2024, 9, 23, 18, 31, 16, 281, DateTimeKind.Local).AddTicks(4764),
                            DateUpdated = new DateTime(2024, 9, 23, 18, 31, 16, 281, DateTimeKind.Local).AddTicks(4765),
                            Gender = "Female",
                            IDEndDate = new DateOnly(2024, 9, 23),
                            IDNumber = "123",
                            NationalityAR = "السعودية",
                            NationalityEN = "Saudi",
                            Passport = "G12",
                            PassportEndDate = new DateOnly(2024, 9, 23),
                            PhoneNumber1 = "",
                            PhoneNumber2 = "",
                            PreviousSchoolAR = "الشمس",
                            PreviousSchoolEN = "",
                            StudentNameAR = "زوز",
                            StudentNameEN = "Zoz",
                            StudentStatusFlag = 0,
                            UpdatedBy = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
